version: 2.1

commands:
  install-dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: HUSKY=0 npm install
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  lint-code:
    docker:
      - image: cimg/node:20.19
    steps:
      - install-dependencies
      - run:
          name: Lint code
          command: npm run lint

  run_tests:
    docker:
      - image: cimg/node:20.19
    steps:
      - install-dependencies
      - run:
          name: Run tests
          command: npm test

  build:
    docker:
      - image: cimg/node:20.19
    steps:
      - install-dependencies
      - run:
          name: Build package
          command: npm run build

workflows:
  ci:
    jobs:
      - lint-code
      - run_tests:
          requires:
            - lint-code
      - build:
          requires:
            - run_tests
